- y_lb.info.yml
```bash
Configuration objects provided by <em class="placeholder">y_lb</em> have unmet depend  
encies: <em class="placeholder">core.entity_form_display.node.landing_page_lb.default  
(scheduler)</em>                                                                      
```
> fix: Dependency error while installing a site

- y_lb.module
I'm assuming here that the `blb_section*` suggestions are only for the `blb_section` theme hook.  
Fixes #52
This includes and supersedes #50 (I just wanted to avoid giving you two PRs that I'm fairly sure would conflict).
Thanks!
> #52: Support non-bootstrap layout builder layouts

- y_lb.install
This enables it in the update but doesn't try to address sites that have already run y_lb_update_9003().
Addresses #59
> fix: enable node revision delete during update

- templates/ws-header.html.twig
**Problem:** 
Our theme has a "Skip to main content" link at the top of the page, but so far Layout Builder pages have broken that functionality and the link has been nonfunctional. The `#main-content` anchor should be at the beginning of the main content of the page, specifically _after_ long lists of navigation links.
**Resolution:**
Since our navigation is build inside of Layout Builder we can't use standard methods (Drupal regions, page.tpl.php) to place the anchor. 
Placing it at the end of `ws-header.html.twig` will: 
- ensure it is after the nav
- let us only add it one place (instead of in every content type's template)
This method could break if the user removes the `ws-header` section from the page. In that case, it's possible the main content is at the top of the page, in which …
> DS-851 Add main-content anchor on layout builder pages

- src/Plugin/Block/NodeShareBlock.php
> fix: Correct mislabeled twitter/linkedin share links

- composer.json
- config/install/core.entity_form_display.node.landing_page_lb.default.yml
- config/install/core.entity_view_display.node.landing_page_lb.default.yml
- config/install/field.field.node.landing_page_lb.field_meta_description.yml
- config/install/field.field.node.landing_page_lb.field_meta_image.yml
- config/install/field.field.node.landing_page_lb.field_meta_tags.yml
- config/install/field.storage.node.field_meta_description.yml
- config/install/field.storage.node.field_meta_image.yml
- config/install/metatag.metatag_defaults.node__landing_page_lb.yml
- y_lb.info.yml
- y_lb.install
resolves [DS-848](https://yusa.atlassian.net/browse/DS-848)
Adds a "Metadata" section to the Landing Page (Layout Builder) content type with two helper fields and lots of descriptions to help content editors make good words. Image and Description are fed into the proper meta and og tags.
> feat(DS-848): Add metatag helper fields and configure meta defaults

- config/install/field.storage.node.field_meta_tags.yml
- y_lb.install
Because prior updates (`y_lb_update_9006, 9011`) import updated config those updates fail because the dependent config isn't imported:
> >  [error]  Configuration <em class="placeholder">core.entity_view_display.node.landing_page_lb.default</em> depends on configuration (<em class="placeholder">field.field.node.landing_page_lb.field_meta_description, field.field.node.landing_page_lb.field_meta_image, field.field.node.landing_page_lb.field_meta_tags</em>) that will not exist after import.
This update rewrites history ... but only if it hasn't been written yet. It adds the dependent config any time `core.entity_view_display.node.landing_page_lb.default` is imported so that updates can proceed. It doesn't matter where a site is when they update, they should now not run into config issues.
> DS-848 Resolve failed updates 

- composer.json
Backport from: https://github.com/ymcatwincities/yn/pull/6651
Fix logs: 
/srv/www/ygtc_github/releases/20230710060311/docroot/core/lib/Drupal/Core/Asset/LibraryDependencyResolver.php) #0 /srv/www/ygtc_github/releases/20230710060311/docroot/core/includes/bootstrap.inc(347): _drupal_error_handler_real(2, 'Undefined array...', '/srv/www/ygtc_g...', 67)
> [Backport YN] Fix not loading bootstrap_styles/aos.local

- composer.json
Addresses: https://yusa.atlassian.net/browse/DS-911
Incorporates: https://www.drupal.org/project/bootstrap_styles/issues/3315218#comment-15168189
Incorporates: https://www.drupal.org/project/bootstrap_styles/issues/3330458#comment-15168188
Context:
```sh
composer why drupal/bootstrap_styles
drupal/bootstrap_layout_builder 2.1.1 requires drupal/bootstrap_styles (^1.1) 
drupal/layout_builder_blocks    1.1.0 requires drupal/bootstrap_styles (^1.1) 
ycloudyusa/y_lb                 2.0.2 requires drupal/bootstrap_styles (*) 
```
After the change
```sh
MacBook-Pro-Andrii:drupal10 podarok$ composer why drupal/bootstrap_styles
drupal/bootstrap_layout_builder 2.1.1                      requires drupal/bootstrap_styles (^1.1)     
drupal/layout_builder_blocks    1.1.0                      requires …
```
> feat: remove patches, limit bootstrap_styles version

- composer.json
- y_lb.info.yml
resolves https://yusa.atlassian.net/browse/DS-912
On config import this error occurs:
```
[Drupal\Core\Config\UnmetDependenciesException]                                                                                                                
Configuration objects provided by <em class="placeholder">y_lb</em> have unmet dependencies: <em class="placeholder">core.entity_form_display.node.landing_pa  
ge_lb.default (entity_browser.browser.images_library), core.entity_view_display.node.landing_page_lb.default (system.menu.footer-menu-center, system.menu.foo  
ter-menu-left, system.menu.footer-menu-right), field.field.node.landing_page_lb.field_meta_image (media.type.image)</em>                                       
```
this adds a bunch of direct dependencies with `openy_features`, …
> fix: DS-912 Add dependency to resolve config import

- y_lb.module
If we update existing website with a lot of content the custom styling of https://github.com/YCloudYUSA/y_lb/blob/main/assets/scss/button.scss breaks the design for all non y_lb related pages.
This PR is aimed adjust the condition of applying the y_lb/main library.  Make sure the y_lb/main is applied only for canonical pages with Layout Builder enabled.
Please, review.
> Do not apply y_lb/main to every entity canonical page

- assets/js/header.js
- templates/blb-section--y-lb.html.twig
- templates/menu--main.html.twig
- y_lb.libraries.yml
This adds on to @aleevas's solution by ensuring that second-level links are accessible, by actually going to their url if they are active.
Also re-adds gutters for multi-column sections. After removing the `px-md-0` class, here's how it looks:
Closes #173
> DS-1181 first lvl menu as link

- y_lb.module
Checks if the library key is set and fixes the following error message:
Error message
Warning: Undefined array key "library" in y_lb_preprocess_html() (line 372 of modules/contrib/y_lb/y_lb.module).
Drupal 10.0.11
PHP version: 8.1.14
> Checks if the library key is set and fixes an error message in y_lb.module

- src/Plugin/migrate/process/MergeRecursive.php
- src/Plugin/migrate/process/YLBSection.php
[DS-1285](https://yusa.atlassian.net/browse/DS-1285)
If we started using a submodule for AF4 demo page migration (https://github.com/YCloudYUSA/y_lb_demo_content/pull/40/commits/31561df1b66c9ffecfe58253190020f0bd951b8f), we need to use these plugins. However, after migrating demo content, all demo content modules are disabled. So, we need to place these plugins in a more general place.
> [DS-1285] Place the common migration/process plugins to Y LB module (were moved from y_lb_demo_content module)

- src/Form/YLBOverridesEntityForm.php
As flagged on the YNCR project, default styles do not show up for "switchable" content types (Branch, Camp, Camp Subpage, Facility).
- log in as admin
- create Branch, Camp, Camp Subpage and Facility content types with layout Builder enabled
- open layout builder 
- click on the override styles button and check if styles are enabled by default
- Styles are enabled in LB for Branch, Camp, Camp Subpage and Facility content types
- Styles aren't enabled in LB for Branch, Camp, Camp Subpage and Facility content types
> fix: Default styles are not appearing on switchable content types

- y_lb.module
Jira issue - [DS-1428](https://yusa.atlassian.net/browse/DS-1428)
- go to homepage
- open the Network tab in the Browser DevTools
- verify that the matchheight.js library **is not** attached
- go to /legacy-home-page
- verify that the matchheight.js library **is** attached
> [DS-1428] Disable 'openy_carnation/matchheight' library for page with LB

- composer.json
Adding over 255 characters to a “Section subtitle” field (where the field is displayed as a textarea) results in a WSOD on page save.
`id: block_content.field_section_subtitle` is defined in 10 different components, but in 7 places it’s defined as string and in three it’s string_long. Somehow just based on the order that modules get installed, the string definition takes precedence, but some components still display the field with the string_textarea widget, which doesn’t do a maxlength check. So… when users try to save more than 255 characters in a field that doesn’t support it AND doesn’t check the length, the site barfs, with something like:
> Drupal\Core\Entity\EntityStorageException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column …
> fix: Add core patch to check maxwidth of textareas

- assets/js/header.js
> DS-1544: Fixed the when click on parent item redirection to homepage.

- modules/y_lb_main_menu_cta_block/config/optional/core.entity_form_display.menu_link_content.main.default.yml
- modules/y_lb_main_menu_cta_block/y_lb_main_menu_cta_block.install
To test:
- go to `/admin/structure/menu/manage/main`
- edit a menu item
- observe "Add existing content block"
-
> DS-1583 fix: Allow CTA Menu Block to reference existing blocks

- src/Plugin/Block/NodeTagsBlock.php
- y_lb.module
https://yusa.atlassian.net/browse/DS-1279
y_lb only works for content pages. If we want to use y_lb in other place like term pages or other system-generated things, we need to add additional logic. This allows y_lb to included on other types of entity types where Layout Builder might be enabled. 
Also adds a "Display as link" option for the Tags block. This is off by default.
> DS-1279 Enable y_lb support on taxonomy pages

- templates/menu--main.html.twig
If `<nolink>` is used in menu items, then `href=""` is shown, which incorrectly links the item. This handles nolinks properly by removing the `href` altogether (which is [valid html](https://stackoverflow.com/a/43340108/2566038))
> DS-1731 Handle nolink menu items properly.

- templates/menu--main.html.twig
Main nav links that are set to link to `#` will pass `isRouted` but will have an empty route. This results in broken code in the link when `href=` has nothing following it.
```
<a href= class="menu-link--level-1" aria-expanded="false" data-toggle="dropdown">
```
This change checks for a route of `<none>` in order to catch that case and not break links.
> bug: Ensure menu links with pound sign "#" do not break

- templates/menu--main.html.twig
_Problem:_ External menu links not working in main navigation
- Updated menu template logic to properly handle non-routed (external) links. 
- Previously, only routed links were generating href attributes, causing external links to be non-functional. 
- This update ensures that both routed and external links are correctly rendered in the navigation.
> Fix external links not working in main navigation menu
