y_lb.info.yml

All submodules are in this package. I think this should be there too.

Use the same package as submodules

---

config/install/bootstrap_styles.settings.yml
css/colors.css
css/layout-builder.css
y_lb.libraries.yml
y_lb.module

- Add predefined colors to the LB background and text color bootstrap styles plugins
- Fix issue with form errors during LB block add/edit process
- Fix required fields display (add asterisk)

Add predefined colors from Colors vocabulary and fix style issues

---

config/install/core.entity_view_display.node.landing_page_lb.default.yml
config/install/node.type.landing_page_lb.yml

- Only allow 1-4 columns
- Disable author/date info [DS-158](https://yusa.atlassian.net/browse/DS-158)

LB UX improvements

---

y_lb.module

https://yusa.atlassian.net/browse/DS-211

DS-211 Uncheck "Display Title" by default

---

config/install/core.base_field_override.node.landing_page_lb.status.yml

resolves https://yusa.atlassian.net/browse/DS-221
To test:
- Enable `y_lb`
- Observe "Published" is unchecked by default.

DS-221 Set new Landing Pages to be unpublished by default

---

composer.json

https://www.drupal.org/project/lb_staff_members_blocks/releases/1.0.0

Include Staff Members component

---

composer.json

Addresses: https://www.drupal.org/project/drupal/issues/3267444#comment-14911034

feat(DS-381): node_revision_delete - Include in distribution w/ default settings

---

y_lb.module

I wasn't sure if it should be restricted to only nodes; I left it working for any entity found.
Fixes #49
Thanks!

#49: Support menu link content with layout builder

---

composer.json

See convo https://yusaslackinstance.slack.com/archives/C03E6SQQ0Q5/p1680203284019729

feat!: Force v2 of entity clone

---

src/Element/WSThemeSettings.php
src/Plugin/Block/NodeShareBlock.php
src/Plugin/Block/NodeTagsBlock.php
src/Plugin/Block/SiteLogoBlock.php
src/Plugin/BootstrapStyles/Style/WSComponentStyleOption.php
src/Plugin/Layout/WsFooterLayout.php
src/WSStyleManager.php
src/WSStyleOptionManager.php
y_lb.api.php
y_lb.install
y_lb.module

Addresses: https://github.com/YCloudYUSA/yusaopeny/pull/8
Fixes: https://yusa.atlassian.net/browse/DS-64

feat: codesniffer and rector fixes for Drupal 10

---

src/EventSubscriber/PrepareLayout.php
src/Plugin/BootstrapStyles/Style/WSComponentStyleOption.php
src/YLbServiceProvider.php

Override "Prepare Layout" Event Subscriber to not show unsaved changes message after changing section configuration.

fix: Override "Prepare Layout"

---

composer.json

Related-to: https://github.com/YCloudYUSA/y_lb/pull/82
Addresses: DS-695

feat: allow v3 of menu_item_extras

---

composer.json
y_lb.info.yml

QA: https://github.com/YCloudYUSA/yusaopeny/pull/77

feat: add pathauto as dependency

---

templates/block--lb-node-share.html.twig

DS-845 [WAVE Accessibility] Article CT (Layout Builder) - Add Social share icons link text

fix: DS-845 Add Social share icons link text

---

composer.json

Chat: https://yusaslackinstance.slack.com/archives/C03E6SQQ0Q5/p1689755086683929
Addresses: https://www.drupal.org/project/layout_builder_save_and_edit/releases/1.0.3

feat: Remove patch, because released

---

composer.json
templates/page--node--layout--discard-revert.html.twig
y_lb.module

To test:
- Edit a Layout Builder page
- Click "Discard changes" or "Revert"
- Observe new styles

feat: DS-832 Add styles to discard and revert pages

---

src/Plugin/Block/NodeTitleBlock.php
src/Plugin/Block/SearchBarBlock.php
src/Plugin/Block/SiteLogoBlock.php
src/Plugin/Block/SiteNameBlock.php
templates/block--lb-node-title.html.twig
templates/block--ws-search-bar.html.twig
templates/block--ws-site-logo.html.twig
templates/block--ws-site-name.html.twig

- Create and open pages with LB enabled (Landing page, Article, Event)
- Make sure that there is no error in DB logs related to the: _"something" is an invalid render array key_

[DS-972] Fix few errors from the DB log.

---

composer.json

Original Issue, this PR is going to fix: https://yusa.atlassian.net/browse/DS-1039
Part-of: https://github.com/YCloudYUSA/yusaopeny/pull/116

fix: Review failing patches

---

templates/block--ws-search-bar.html.twig

https://yusa.atlassian.net/browse/DS-1011

fix: DS-1011 Add search bar input label

---

assets/css/layout-builder.css
assets/scss/layout-builder.scss

Adds off-canvas styles for alerts to work with https://www.drupal.org/project/openy_carnation/issues/3403176

DS-827 fix: Add alert styles and clean up off-canvas forms.

---

y_lb.module

fix: support canonical non-fieldable entity views

---

y_lb.module

[DS-1023](https://yusa.atlassian.net/browse/DS-1023)
We don't want to attach WS-specific libraries on the pages that don't use LB.

[DS-1023] Attach WS libraries only if a page uses LB.

---

config/install/core.entity_view_display.node.landing_page_lb.default.yml
src/Plugin/Block/CopyrightBlock.php
src/Plugin/Block/SocialBlock.php

https://yusa.atlassian.net/browse/DS-1079

fix: Missed content blocks && create new blocks

---

composer.json

https://www.drupal.org/project/drupal/issues/3049332
https://yusa.atlassian.net/browse/DS-1426

fix: Add patch for LB block missing/broken error

---

composer.json

fix: Update MR to patch

---

src/Plugin/Block/NodeShareBlock.php
y_lb.libraries.yml

DS-1440 Update bootstrap icons library because Elon said so

---

config/install/core.entity_form_display.node.landing_page_lb.default.yml
config/install/node.type.landing_page_lb.yml
y_lb.install

https://yusa.atlassian.net/browse/DS-1493
To test:
- /node/add/landing_page_lb
- Observe Scheduling options is available
- (can test scheduling, but cron must be running)

DS-1493 fix: Enable scheduler.

---

assets/js/header.js

Fixed the issue with header main navigation. When we click on parent menu items with href "<front>",

DS-1544: Fixed the when click on parent item redirection to homepage.

---

assets/js/header.js
y_lb.libraries.yml

Jira: [DS-1410](https://yusa.atlassian.net/browse/DS-1410)

[DS-1410] - Add a fix for cases when the right menu was removed from the header section

---

assets/js/media_modal.js
assets/scss/main-menu.scss
y_lb.libraries.yml

https://yusa.atlassian.net/browse/DS-1506
https://yusa.atlassian.net/browse/DS-1591
https://yusa.atlassian.net/browse/DS-1520

[DS-1506][DS-1591][DS-1520]: fix style and fix media modal window

---

src/WSOverrideLayoutBuilder.php
src/WSOverrideLayoutBuilderInterface.php
y_lb.module
y_lb.plugin_type.yml
y_lb.services.yml

Jira issue [DS-1653](https://yusa.atlassian.net/browse/DS-1653)
How to check:
```yml
{module_name}.{component_id}_override:
block_type: lb_testimonials
library: {module_name}/lb_testimonials_override
override: false
active_colorways:
- small_y*
- '*green'
```

[DS-1653] - Initial implementation of the WS Override plugin Manager

---

src/WSOverrideLayoutBuilder.php

fix, to correctly check the applicability of the component

fix: ws_override applicable for component

---

src/Plugin/Block/NodeTitleBlock.php

Jira issue: [DS-1662](https://yusa.atlassian.net/browse/DS-1662)
The new design for Small Y requires info about the author and published date.
So, I've added it inside the block to allow the use of these variables inside templates.

[DS-1662] - Add variables for author and published time for the NodeTitle block

---

config/install/y_lb.admin.settings.yml
src/Form/SettingsForm.php
src/Plugin/Block/SocialBlock.php
templates/ws-social-links-block.html.twig
y_lb.links.menu.yml
y_lb.module
y_lb.routing.yml

Jira: [DS-1674](https://yusa.atlassian.net/browse/DS-1674)
- verify that old Social links in the footer work on existing pages
- log as admin
- go to` /admin/openy/settings/y-lb`
- verify that you can see the form with settings for the social links block
- fill out the fields
- verify that you can't save the form with a non-valid URL (ex. htts://examplecom)
- save the form
- create a new LP with LB
- verify that the social links use the URL from the settings form
- verify that if you leave one of the fields empty, then this link doesn't display inside the block

[DS-1674] Add configuration options for the Social Links block

---

assets/js/header.js
y_lb.libraries.yml

**Problem:** If the right menu (right_menu) is missing, the max_available_width value is calculated incorrectly, which may lead to an incorrect display mode detection. As a result, the burger menu does not appear on mobile devices.
Check the menu
**Expected result:** The menu should be collapsed into burger

[ITCP-173] Fix burger menu for mobile
